### ISSUE TITLE
Not getting connected

### ISSUE THREAD

**Issue by anitaa1990** [NewtronLabs/EasyBluetooth#1]
Hey, nice library.:)

So I have a requirement to create two apps, where one app acts as the serer and the other app as the client. I have installed one app in one device and another app in another device.

I am not able to connect between the two devices. The onConnectionFailed keeps getting called. Not sure why.

**Comment by NewtronLabs** [comment]
Hello @anitaa1990,

Thank you, we are glad you like it!

Could you share with us the device specs? Also, if you have any logs that you can share that may help us narrow down the issue. 

Thank you,
Easy Bluetooth Team
