### ISSUE TITLE
The library does not support gradle version higher than 3.0.+

### ISSUE THREAD

**Issue by georgeRCluj** [NewtronLabs/EasyBluetooth#2]
I am using Gradle 3.1.2 and it tells me that "Android Gradle version not supported. Maximum supported version: 3.0.+"

**Comment by NewtronLabs** [comment]
Hi @georgeRCluj, 

The support for Gradle 3 is still in its alpha stages and undergoing testing. In the meantime you can use the alpha version which should resolve this problem.

```
dependencies {
    classpath 'com.android.tools.build:gradle:3.0.1'
    classpath "com.newtronlabs.android:plugin:2.0.0.alpha"
}
```
The other option is to use Gradle 2.

Please let us know if you have any questions. 

Newtron Labs
Solving problems so you don't have to.
